linkguarder_activitycontrol_node_query:
    path: /ac_node_query
    defaults: { _controller: linkguarder.activitycontrol.controller:node_query }

linkguarder_activitycontrol_webhook:
    path: /notify
    defaults: { _controller: linkguarder.activitycontrol.controller:webhook_notification }
