linkguarder_activitycontrol_webhook:
    path: /activitycontrol/webhook/notify
    defaults: { _controller: linkguarder.activitycontrol.controller:webhook_notification }
    methods: [POST]

linkguarder_activitycontrol_node_query:
    path: /activitycontrol/query
    defaults: { _controller: linkguarder.activitycontrol.controller:node_query }
    methods: [POST]

linkguarder_activitycontrol_controller:
    path: /activitycontrol/{name}
    defaults: { _controller: linkguarder.activitycontrol.controller:handle }