services:
    linkguarder.activitycontrol.listener:
        class: linkguarder\activitycontrol\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@user'
            - '@auth'
            - '@language'
        tags:
            - { name: event.listener }
    linkguarder.activitycontrol.controller:
        class: linkguarder\activitycontrol\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'