services:
    linkguarder.activitycontrol.listener:
        class: linkguarder\activitycontrol\event\main_listener
        arguments:
            - '@config'
            - '@user'
            - '@auth'
            - '@language'
        tags:
            - { name: event.listener }
    linkguarder.activitycontrol.controller:
        class: linkguarder\activitycontrol\controller\main_controller
        arguments:
            - '@template'
