services:
    linkguarder.activitycontrol.listener:
        class: linkguarder\activitycontrol\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@user'
            - '@auth'
            - '@language'
            - '@dbal.conn' # Service pour la base de données
            - '@group_helper' # Service pour gérer les groupes
        tags:
            - { name: event.listener }
    linkguarder.activitycontrol.controller:
        class: linkguarder\activitycontrol\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    # Squelette du service de synchronisation IP bans (à implémenter)
    linkguarder.activitycontrol.ip_ban_sync:
        class: linkguarder\activitycontrol\service\ip_ban_sync
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@request'
        tags:
            - { name: cron.task }