services:
    linkguarder.activitycontrol.listener:
        class: linkguarder\activitycontrol\event\listener
        arguments:
            - '@controller.helper'
            - '@template'
            - '@config'
            - '@user'
            - '@auth'
            - '@language'
            - '@dbal.conn' # Service pour la base de données
            - '@group_helper' # Service pour gérer les groupes
            - '@linkguarder.activitycontrol.ip_reporter' # Service de signalement d'IPs
        tags:
            - { name: event.listener }
    linkguarder.activitycontrol.controller:
        class: linkguarder\activitycontrol\controller\main
        arguments:
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@user'

    # Service de synchronisation IP bans
    linkguarder.activitycontrol.ip_ban_sync:
        class: linkguarder\activitycontrol\service\ip_ban_sync
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@user'
            - '@auth'
            - '@request'
        tags:
            - { name: cron.task }

    # Service de signalement d'IPs au serveur central
    linkguarder.activitycontrol.ip_reporter:
        class: linkguarder\activitycontrol\service\ip_reporter
        arguments:
            - '@config'
            - '@log'
            - '%core.root_path%ext/linkguarder/activitycontrol'